import Head from "next/head";
import Login from "../login/login";
import { type NextPage } from "next";
import SubscriptionStatus from "./subscription-status";
import { Products } from "./products";
import { Session } from "next-auth";
import { getServerAuthSession } from "~/server/auth";
import { api } from "~/trpc/server";
import UpgradeButton from "../buttons/upgrade-button";
import { type RouterOutputs } from "~/trpc/shared";
import ManageBillingButton from "./manage-billing-button";

const Dashboard: NextPage = async () => {
  // const { data: subscriptionStatus, isLoading } =
  //   api.user.subscriptionStatus.useQuery();
  // const { data: status } = api.subscription.subscriptionStatus.useQuery();
  // console.log("subscriptionStatus", subscriptionStatus);
  // console.log("status", status);
  const session = await getServerAuthSession();

  if (!session) {
    return (
      <>
        <Head>
          <title>T3 Stripe</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
          <h1 className="text-5xl font-extrabold leading-normal text-gray-700">
            T3 <span className="text-[#5433FF]">Stripe</span> Dashboard
          </h1>
          <p className="text-2xl text-gray-700">Actions:</p>
          <div className="mt-3 flex flex-col items-center justify-center gap-4">
            <Login />
            {/* <SubscriptionStatus /> */}
          </div>
        </main>
      </>
    );
  }
  const subscriptionStatus = await api.user.subscriptionStatus();

  return (
    <>
      <Head>
        <title>T3 Stripe</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700">
          T3 <span className="text-[#5433FF]">Stripe</span> Dashboard
        </h1>
        <p className="text-2xl text-gray-700">Actions:</p>
        <div className="mt-3 flex flex-col items-center justify-center gap-4">
          <Login />
          {/* <SubscriptionStatus /> */}
          {subscriptionStatus && (
            <>
              <p className="text-xl text-gray-700">
                Your subscription is {subscriptionStatus}.
              </p>
              <ManageBillingButton />
            </>
          )}

          {!subscriptionStatus && (
            <>
              <p className="text-xl text-gray-700">You are not subscribed!!!</p>
              <UpgradeButton />
            </>
          )}
        </div>
      </main>
    </>
  );
};

export default Dashboard;
